language: ruby
rvm:
  - 2.5.3
services:
  - postgresql
before_install:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database scoring_processing_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - export RAILS_ENV=test
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
