default: &default
  adapter: postgresql
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

test:
  <<: *default
  database: scoring_processing_test
